### PR TITLE
Allow psr/http-message 2

### PR DESCRIPTION
**Pull request by simoheinonen**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | 

#### Summary

Allow psr/http-message ^2.0

### CODE REVIEW

**Comment by veewee** [comment]
Thanks for the PR. Dependabot also tried the same this morning, but it seems to fail on static analysis.
Can you take a look at it?

**Comment by simoheinonen** [comment]
Couldn't figure it out but looks like it's happening in master too

**Comment by veewee** [comment]
Ok, I'll try to look into it later this week

**Comment by veewee** [comment]
The issue here is related to httplug/promise 1.2 and the 
`Plugin` not specifying the generic `Promise`'s `<T>` type.
It's on their radar: https://github.com/php-http/client-common/issues/235

**Pull request merged**
